### PR TITLE
test android new landing

### PR DESCRIPTION
**Pull request by bilalawan321**

### CODE REVIEW

**Comment by bwaheed** [comment]
For OS 10 and 7 its working fine. But for OS 4.4.4 2 test cases are failing which are mention below.
1: test_ui_elements_smoke.
Please verify it.

**Comment by nedo** [comment]
Change looks good

**Comment by nedo** [comment]
`test_back_and_forth_smoke` is getting failed, it did not handle @bilalawan321 @bwaheed

**Comment by bilalawan321** [comment]
@nedo kindly share error with me.

**Comment by nedo** [comment]
@bilalawan321 looks good,please merge it in your repo

**Pull request closed without merging**
